# Generated by https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels-monthly-means?tab=form
# Monthly mean MSLP for full ERA5 dataset
# 20N-90N, Nov-Apr (cold season)

import cdsapi

import iris

from constrain import regrid_to_coarsest

c = cdsapi.Client()

c.retrieve(
    'reanalysis-era5-single-levels-monthly-means',
    {
        'product_type': 'monthly_averaged_reanalysis',
        'format': 'netcdf',
        'variable': 'mean_sea_level_pressure',
        'year': list(range(1940, 2023)),
        'month': ['01', '02', '03', '04', '11', '12'],
        'time': '00:00',
        'area': [90, -180, 20, 180],
    },
    'era5_monthly_mean_mslp_20N-90N_NDJFMA.nc'
)

# Regrid the ERA5 data to the coarsest CMIP6 grid
cube = iris.load_cube("era5_monthly_mean_mslp_20N-90N_NDJFMA.nc")
for axis in ("x", "y"):
    cube.coord(axis=axis, dim_coords=True).guess_bounds()

coarse_cube = regrid_to_coarsest(cube)

# Regridding extrapolates to extra latitudes not downloaded so reselect area
coarse_cube = coarse_cube.intersection(latitude=(20, 90))

iris.save(coarse_cube, "era5_monthly_mean_CanESM5_grid_mslp_20N-90N_NDJFMA.nc")

