# Generated by https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels-monthly-means?tab=form
# Monthly mean MSLP for full ERA5 dataset
# 20N-90N, Nov-Apr (cold season)

import cdsapi

c = cdsapi.Client()

c.retrieve(
    'reanalysis-era5-single-levels-monthly-means',
    {
        'product_type': 'monthly_averaged_reanalysis',
        'format': 'netcdf',
        'variable': 'mean_sea_level_pressure',
        'year': list(range(1940, 2023)),
        'month': ['01', '02', '03', '04', '11', '12'],
        'time': '00:00',
        'area': [90, -180, 20, 180],
    },
    'era5_monthly_mean_mslp_20N-90N_NDJFMA.nc'
)
